### ISSUE TITLE
Error 0x80242006

### ISSUE THREAD

**Issue by sonnenx** [DCourtel/Wsus_Package_Publisher#30] opened 2020-05-06 15:50 UTC
Hello, I have WPP installed on Win2019 and workstations on Win10 2004 and 1909. I can publish and download the package (eg Java 8, Edge Chromium) but they do not install, they display error message 0x80242006. I tested on 3 computers, MS updates distributed by Wsus install correctly. What could be the problem?

**Comment by henkelm** [comment] 2020-05-07 08:56
I have the same Problem too. The error message indicates incorrect or corrupt metadata. Does somebody has any idea?

**Comment by henkelm** [comment] 2020-05-07 09:04
0x80242006

WU_E_UH_INVALIDMETADATA

A handler operation could not be co because the update contains invalid

**Comment by DCourtel** [comment] 2020-05-07 09:06
Are you creating the package from the WSUS server or from an admin computer?

**Comment by sonnenx** [comment] 2020-05-07 09:08
From WSUS Server.

**Comment by henkelm** [comment] 2020-05-07 09:09
The package was created on the WSUS server with local WPP on this server.

**Comment by DCourtel** [comment] 2020-05-07 09:13
What are your WSUS server and console version?
![image](https://user-images.githubusercontent.com/13787283/81276809-cfba4d80-9053-11ea-9da6-8d9bafc10a89.png)

**Comment by sonnenx** [comment] 2020-05-07 09:16
![obraz](https://user-images.githubusercontent.com/37338780/81276974-0abc8100-9054-11ea-9762-a7efac144393.png)
![obraz](https://user-images.githubusercontent.com/37338780/81277039-21fb6e80-9054-11ea-87f8-3bfcd2c7390c.png)

**Comment by henkelm** [comment] 2020-05-07 09:17
Windows Server 2016 , Version 1607 (Build 14393.3630)
![image](https://user-images.githubusercontent.com/64955558/81277093-3475a800-9054-11ea-90ca-4ba2334bbf0c.png)
![image](https://user-images.githubusercontent.com/64955558/81277174-55d69400-9054-11ea-81c9-84ad90d3d94b.png)

**Comment by DCourtel** [comment] 2020-05-07 09:43
When was published the last working update?

**Comment by henkelm** [comment] 2020-05-07 09:44
One cannot say that exactly, the problem has existed for a few weeks.

**Comment by sonnenx** [comment] 2020-05-07 09:51
Never. This is a new installation.

**Comment by DCourtel** [comment] 2020-05-09 15:44
I had the same issue with test packages but the issue gone after a server reboot.

**Comment by sonnenx** [comment] 2020-05-10 13:02
I cleaned C:\Windows\SoftwareDistribution\Download on the test machine, restart the WSUS server and the error still occurs.

**Comment by henkelm** [comment] 2020-05-11 06:42
A restart could not fix the problem

**Comment by henkelm** [comment] 2020-05-11 07:20
Updates are also affected that definitely worked when they were created

**Comment by DCourtel** [comment] 2020-05-11 07:26
Can you try to revise a faulty update, wipe out the SoftwareDistibution folder on a client computer and give it another try?

**Comment by henkelm** [comment] 2020-05-11 08:00
I tested that, unfortunately not a success

**Comment by henkelm** [comment] 2020-05-11 08:01
I also uninstalled Endpoint Protection Protection for a test, with the same result.

**Comment by henkelm** [comment] 2020-05-11 11:12
I tested a little further, the problem does not occur with Windows 10 1903 or 1909. The error only seems to exist on Windows 10 2004.

**Comment by DCourtel** [comment] 2020-05-11 12:28
@sonnenx can you check if the error appears only on Windows 10 2004?

**Comment by sonnenx** [comment] 2020-05-11 13:00
Yes, after restarting the server, on W10 1909 workstations the packages install correctly, but for W10 2004 the error still occurs.

**Comment by DCourtel** [comment] 2020-05-11 13:20
@sonnenx @henkelm can you run WinVer command and tell me what is the full release number?

**Comment by sonnenx** [comment] 2020-05-11 13:25
![obraz](https://user-images.githubusercontent.com/37338780/81566721-92c7c100-939b-11ea-94a4-20f6d83bf3db.png)

**Comment by DCourtel** [comment] 2020-05-11 13:25
For Windows 10 1909

**Comment by sonnenx** [comment] 2020-05-11 13:29
![obraz](https://user-images.githubusercontent.com/37338780/81567115-226d6f80-939c-11ea-8809-609638617147.png)

**Comment by henkelm** [comment] 2020-05-11 13:35
![image](https://user-images.githubusercontent.com/64955558/81567722-ff8f8b00-939c-11ea-8118-304ffda967a5.png)

**Comment by henkelm** [comment] 2020-05-11 13:38
![image](https://user-images.githubusercontent.com/64955558/81567963-61e88b80-939d-11ea-8a1e-62aaf73b3b9f.png)
1909 with no error

**Comment by DCourtel** [comment] 2020-05-13 16:52
What did you define as applicability rules?
![image](https://user-images.githubusercontent.com/13787283/81841521-e3c9e780-954a-11ea-9163-4d61085e7eca.png)

**Comment by sonnenx** [comment] 2020-05-14 07:25
MS Edge Chromium:
![obraz](https://user-images.githubusercontent.com/37338780/81905248-c174b000-95c4-11ea-8c7b-f806cbb0b75e.png)
![obraz](https://user-images.githubusercontent.com/37338780/81905286-cd607200-95c4-11ea-81cc-347981ea1384.png)

**Comment by sonnenx** [comment] 2020-05-14 07:26
Java 8:
![obraz](https://user-images.githubusercontent.com/37338780/81905413-f2ed7b80-95c4-11ea-97e0-354f9e4481ab.png)
![obraz](https://user-images.githubusercontent.com/37338780/81905448-000a6a80-95c5-11ea-9cdb-d8e4fc315afc.png)

**Comment by henkelm** [comment] 2020-05-14 08:22
Firefox 76.0.1
![image](https://user-images.githubusercontent.com/64955558/81910842-c63d6200-95cc-11ea-8488-b189edb9c8ef.png)
![image](https://user-images.githubusercontent.com/64955558/81910919-dce3b900-95cc-11ea-901f-09c974eb295e.png)

**Comment by henkelm** [comment] 2020-05-14 08:25
Adobe Acrobat Reader DC Update 20.006.20042 
from Catalog subscription
![image](https://user-images.githubusercontent.com/64955558/81911139-292ef900-95cd-11ea-952d-9c84975e0462.png)
![image](https://user-images.githubusercontent.com/64955558/81911164-36e47e80-95cd-11ea-9381-e4fd35bb632b.png)

**Comment by henkelm** [comment] 2020-05-26 04:58
Is there already a solution here? The error is slowly becoming critical in our infrastructure.

**Comment by R6Racer** [comment] 2020-05-29 04:35
Hello, we have the same problems here. WPP Updates work on Windows 10 < 2004. On Windows 10 2004 the error 0x80242006 occours.

**Comment by Andyt8** [comment] 2020-05-29 05:53
I found the same problem. According to my research the error message started with Windows 10 2004 on our old WSUS Server (Windows Server 2016) which is able to share all updates to Windows 10 1909 and older.

However, Windows 10 2004 is still able to get updates from our WSUS, if that updates contains exe files. The error 0x80242006 occour only for all updates with msi-files. I checked the download cache and the updates are successfully downloaded. If I open one of them (cab-file from c:\windows\softwaredistribution\download\random-folder) and try to install the msi-file, then it is successful.

**Comment by Andyt8** [comment] 2020-05-29 08:59
Additional information from my research...   If I create an application update of a msi-file by using exe-file (including script which use msiexec.exe and the included msi-file for installation), then the update is finished successful.

It looks like, windows 10 2004 changed, how it works with msi files from wsus? I tried already several fresh installations, which includes the latest 2004 KB from Microsoft.

**Comment by titeck13** [comment] 2020-05-30 12:35
I found that when update is msi file, but i don't know how to resolve

2020/05/29 12:10:04.7778014 744   6780  Handler         * START *   MSI Install
2020/05/29 12:10:04.7778026 744   6780  Handler         Updates to Install = 1
2020/05/29 12:10:04.7799814 744   6780  Handler         MSI update {50361EB5-CF73-4E77-B878-E8E7CC20D812}.4 using source image from 1 CABs.
2020/05/29 12:10:05.1579343 744   6780  Handler         Server-relative repair path specified, but the server did not provide a root path.
2020/05/29 12:10:05.1579360 744   6780  Handler         Failed to normalize repair paths
2020/05/29 12:10:05.1605206 744   6780  Handler         Operation failed at update 0, Exit code = 0x80242006
2020/05/29 12:10:05.1605225 744   6780  Handler         * END *   MSI Install

**Comment by esuger** [comment] 2020-06-01 18:53
I can confirm the issue has appeared for us on any machine that is running Windows 10 May Update 2020.  (e.g. 2004).   Same error code to.

This issue even occurs using the Adobe Catalog created updates.


I can also confirm that the work around using the Custom Update does work, its just a pain to create a custom update for every MSI.  Especially for Adobe Reader.

**Comment by DCourtel** [comment] 2020-06-02 16:22
Thanks everyone for your feedback. We have contacted Microsoft for further investigations. I will let you know.

**Comment by DCourtel** [comment] 2020-06-03 05:32
That should be fixed in the next patch Tuesday.

**Comment by Andyt8** [comment] 2020-06-03 05:37
Wow, thank you for your information. Good news. That was really fast :-) . Hopefully it is true ;-) .

edit: I mean, that the fix really solve the whole problem.

**Comment by titeck13** [comment] 2020-06-03 06:46
thank you

**Comment by jmahmens** [comment] 2020-06-07 10:42
I have the same problem with win 20h1 clients but with a server 2012R2. The fix, maybe provided by Microsoft, will fix the clients or the server? Log's an clients contains similar lines for other than Adobe Catalog. Here are the Mozilla updates found.

**Comment by esuger** [comment] 2020-06-09 17:57
I can confirm that today's  (June 9th 2020) cumulative update for Windows 10 2004 seems to fix the issue.  

I installed the cumulative updates to both the Windows 10 client and Windows WSUS server and now the Adobe Reader updates install without error.

**Comment by jmahmens** [comment] 2020-06-09 18:39
Yes KB4557957 solves this issue.

**Comment by DCourtel** [comment] 2020-06-09 20:56
I confirm that KB4557957 fixes this issue.

**Closed as completed by DCourtel** 2020-06-09 20:56 UTC
